[WIP] Deprecated and added new SSL settings
logstash-plugins/logstash-filter-elasticsearch pull request #168
Opened 2023-03-07 17:52 UTC by edmocosta

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

2023-03-09 17:03 UTC, andsel requested changes
Left some comments, that are quite similar to the observations done for output and input.

2023-03-09 21:16 UTC, edmocosta commented on lib/logstash/filters/elasticsearch.rb
> +    return ssl_options unless @ssl_enabled
Good catch! Setting the `trust_strategy` independently of the `ssl => true` option is actually a condition of the input plugin ([L439](https://github.com/logstash-plugins/logstash-input-elasticsearch/blob/main/lib/logstash/inputs/elasticsearch.rb#L439)). I've mistakenly applied it here as well. 

It was also missing an extra condition to keep it backward compatible. I've pushed the changes and added a comment to explain the intention. The main idea is to have the same functionality for the `ssl_enabled` flag across the three Elasticsearch plugins.

2023-03-10 08:19 UTC, andsel requested changes
Left a nitpick style note

2023-03-10 08:19 UTC, andsel commented on lib/logstash/filters/elasticsearch.rb
> +      raise(LogStash::ConfigurationError, 'Use either "ssl_certificate_authorities/ca_file" or "ssl_truststore_path" when configuring the CA certificate')
```suggestion
      raise LogStash::ConfigurationError, 'Use either "ssl_certificate_authorities/ca_file" or "ssl_truststore_path" when configuring the CA certificate'
```

2023-03-10 08:19 UTC, andsel commented on lib/logstash/filters/elasticsearch.rb
> +      raise(LogStash::ConfigurationError, 'Use either "ssl_certificate" or "ssl_keystore_path/keystore" when configuring client certificates')
```suggestion
      raise LogStash::ConfigurationError, 'Use either "ssl_certificate" or "ssl_keystore_path/keystore" when configuring client certificates'
```

2023-03-10 08:19 UTC, andsel commented on lib/logstash/filters/elasticsearch.rb
> +      raise(LogStash::ConfigurationError, 'Multiple values on "ssl_certificate_authorities" are not supported by this plugin') if ssl_certificate_authorities.size > 1
```suggestion
      raise LogStash::ConfigurationError, 'Multiple values on "ssl_certificate_authorities" are not supported by this plugin' if ssl_certificate_authorities.size > 1
```

2023-03-10 08:19 UTC, andsel commented on lib/logstash/filters/elasticsearch.rb
> +      raise(LogStash::ConfigurationError, 'You must set both "ssl_certificate" and "ssl_key" for client authentication')
```suggestion
      raise LogStash::ConfigurationError, 'You must set both "ssl_certificate" and "ssl_key" for client authentication'
```

2023-03-10 10:43 UTC, edmocosta commented
> Left a nitpick style note

Thank you again for reviewing it, @andsel. I've addressed your suggestions plus the [suggestion #1](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1118#discussion_r1131890635 ) and [suggestion #2](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1118#discussion_r1131892391) made on the output plugin.

2023-03-10 13:23 UTC, andsel approved these changes
LGTM

Just update the 
```
deprecated[8.8.0, Replaced by
```
 to refer to the plugin's version instead of Logstash one.

2023-03-10 13:38 UTC, kaisecheng commented on CHANGELOG.md
> +    - `ssl_truststore_path`: he JKS truststore to validate the server's certificate
```suggestion
    - `ssl_truststore_path`: The JKS truststore to validate the server's certificate
```

2023-03-10 16:53 UTC, edmocosta commented on lib/logstash/filters/elasticsearch.rb
> +      raise LogStash::ConfigurationError, 'Using an "ssl_certificate" requires an "ssl_key"' unless ssl_key
I'm gonna move on with this PR and merge it! If that's a mistake I can submit another PR to fix it! Thanks!

2023-03-10 16:53 UTC, merged

2023-04-06 13:13 UTC, djschny commented
How can I tell what version of Elastic stack this is in?

2023-09-12 09:33 UTC, tommycahir commented
I am just running v3.15.2 and I am seeing an error saying " Unknown setting 'ssl_certificate_verification' for elasticsearch" when using this filter

2023-09-12 10:07 UTC, edmocosta commented
Hi @tommycahir!

The `ssl_certificate_verification` setting does not exist for this filter. I think the correct one is [ssl_verification_mode](https://www.elastic.co/guide/en/logstash/current/plugins-filters-elasticsearch.html#plugins-filters-elasticsearch-ssl_verification_mode) :)